import { Link } from 'react-router-dom';
import styles from './LegalPage.module.css';

export default function PrivacyPage() {
  return (
    <div className={styles.page}>
      <div className={styles.content}>
        <Link to="/login" className={styles.backLink}>&larr; Back</Link>
        <h1>Privacy Policy</h1>
        <p className={styles.updated}>Last updated: March 2026</p>

        <h2>What Data We Collect</h2>
        <p>
          When you use Dex Insights Core, we collect and store the following data associated with your account:
        </p>
        <ul>
          <li><strong>Account information:</strong> Your email address and hashed password (managed by Supabase Auth).</li>
          <li><strong>Dexcom credentials:</strong> Your Dexcom Share username and password, stored securely to fetch your glucose data on your behalf.</li>
          <li><strong>Glucose readings:</strong> Continuous glucose monitor (CGM) data retrieved from the Dexcom Share API, including glucose values, trends, and timestamps.</li>
          <li><strong>Pattern analysis:</strong> Detected glucose patterns (e.g., morning spikes, nocturnal lows) and daily statistics computed from your readings.</li>
          <li><strong>AI-generated insights:</strong> Personalized summaries and recommendations generated by analyzing your glucose data.</li>
        </ul>

        <h2>How Your Data Is Stored</h2>
        <p>
          All data is stored in a Supabase-hosted PostgreSQL database with encryption at rest. Supabase is SOC2 Type II compliant.
          Row-level security policies ensure that each user can only access their own data.
        </p>

        <h2>Who Can Access Your Data</h2>
        <p>
          Only you can access your data through your authenticated account. We do not share, sell, or provide
          your data to any third parties. Your glucose data and Dexcom credentials are never exposed to other users.
        </p>

        <h2>AI Processing</h2>
        <p>
          Your glucose data is sent to the Anthropic API (Claude) to generate personalized insights.
          This data is used solely for generating your insights and is subject to
          Anthropic's data handling policies. No glucose data is retained by Anthropic after processing.
        </p>

        <h2>Analytics & Tracking</h2>
        <p>
          We do not use any third-party analytics, advertising trackers, or cookies beyond
          what is necessary for authentication.
        </p>

        <h2>Data Retention & Deletion</h2>
        <p>
          Your data is retained as long as your account is active. You may request complete
          deletion of your account and all associated data at any time by contacting us.
          Upon deletion, all glucose readings, patterns, insights, and credentials are permanently removed.
        </p>

        <h2>Contact</h2>
        <p>
          For privacy-related questions or data deletion requests, please contact us through the application.
        </p>
      </div>
    </div>
  );
}
